-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WorkflowFacade
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WorkflowFacade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WorkflowFacade` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `WorkflowFacade` ;

-- -----------------------------------------------------
-- Table `WorkflowFacade`.`ROLE_MASTER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WorkflowFacade`.`ROLE_MASTER` (
  `ROLE_CDE` VARCHAR(10) NOT NULL COMMENT '',
  `ROLE_DESC` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`ROLE_CDE`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkflowFacade`.`USER_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WorkflowFacade`.`USER_ROLE` (
  `ID` VARCHAR(45) NOT NULL COMMENT '',
  `ROLE_CDE` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `ROLE_REF_idx` (`ROLE_CDE` ASC)  COMMENT '',
  CONSTRAINT `ROLE_REF`
    FOREIGN KEY (`ROLE_CDE`)
    REFERENCES `WorkflowFacade`.`ROLE_MASTER` (`ROLE_CDE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkflowFacade`.`USER_AUTH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WorkflowFacade`.`USER_AUTH` (
  `ID` VARCHAR(45) NOT NULL COMMENT '',
  `EMAIL_ADDRESS` VARCHAR(45) NULL COMMENT '',
  `PASSWORD` VARCHAR(100) NULL COMMENT '',
  `WORKFLOW_REF_USERID` VARCHAR(45) NULL COMMENT '',
  `IS_ACTIVE` TINYINT(1) NULL COMMENT '',
  `IS_EXPIRED` TINYINT(1) NULL COMMENT '',
  `IS_SUSPENDED` TINYINT(1) NULL COMMENT '',
  `CREATED_DATE` DATETIME NULL COMMENT '',
  `UPDATED_DATE` DATETIME NULL COMMENT '',
  `IS_AUTHORIZATION_ONLY` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  CONSTRAINT `USER_ROLE_REF`
    FOREIGN KEY (`ID`)
    REFERENCES `WorkflowFacade`.`USER_ROLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkflowFacade`.`ROLE_PREVILIGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WorkflowFacade`.`ROLE_PREVILIGE` (
  `ROLE_CDE` VARCHAR(10) NOT NULL COMMENT '',
  `CAN_START_CASE` TINYINT(1) NOT NULL COMMENT '',
  `CAN_SEND_MESSAGE` TINYINT(1) NOT NULL COMMENT '',
  `CAN_CLAIM_TASK` TINYINT(1) NOT NULL COMMENT '',
  `CAN_VIEWONLY_TASK` TINYINT(1) NOT NULL COMMENT '',
  `CAN_SEARCH_TASK` TINYINT(1) NOT NULL COMMENT '',
  `CAN_PURGE_CASE` TINYINT(1) NOT NULL COMMENT '',
  `CAN_SUSPEND_CASE` TINYINT(1) NOT NULL COMMENT '',
  `CAN_PARTICIPATE_CASE` TINYINT(1) NOT NULL COMMENT '',
  `CAN_SEE_REPORTS` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`ROLE_CDE`)  COMMENT '',
  CONSTRAINT `ROLE_REF_MASTER`
    FOREIGN KEY (`ROLE_CDE`)
    REFERENCES `WorkflowFacade`.`ROLE_MASTER` (`ROLE_CDE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkflowFacade`.`MANAGED_WORKFLOWS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WorkflowFacade`.`MANAGED_WORKFLOWS` (
  `WORKFLOW_PROCESS_ID` VARCHAR(100) NOT NULL COMMENT '',
  `WORKFLOW_NAME` VARCHAR(100) NULL COMMENT '',
  `BUSINESSKEY_PREFIX` VARCHAR(45) NULL COMMENT '',
  `BUSINESSKEY_SUFFIX` VARCHAR(45) NULL COMMENT '',
  `CREATED_DATE` DATETIME NULL COMMENT '',
  `UPDATED_DATE` DATETIME NULL COMMENT '',
  PRIMARY KEY (`WORKFLOW_PROCESS_ID`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `WorkflowFacade`.`WORKFLOW_ROLE_CONFIG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WorkflowFacade`.`WORKFLOW_ROLE_CONFIG` (
  `ROLE_CDE` VARCHAR(10) NOT NULL COMMENT '',
  `WORKFLOW_PROCESS_ID` VARCHAR(100) NOT NULL COMMENT '',
  `CANSTARTINSTANCE` TINYINT(1) NULL COMMENT '',
  `CANSENDMESSAGE` TINYINT(1) NULL COMMENT '',
  INDEX `REF1_idx` (`ROLE_CDE` ASC)  COMMENT '',
  INDEX `WORKFLOW_REF1_idx` (`WORKFLOW_PROCESS_ID` ASC)  COMMENT '',
  CONSTRAINT `REF1`
    FOREIGN KEY (`ROLE_CDE`)
    REFERENCES `WorkflowFacade`.`ROLE_MASTER` (`ROLE_CDE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `WORKFLOW_REF1`
    FOREIGN KEY (`WORKFLOW_PROCESS_ID`)
    REFERENCES `WorkflowFacade`.`MANAGED_WORKFLOWS` (`WORKFLOW_PROCESS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkflowFacade`.`WORKFLOW_START_SEND_CONFIG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WorkflowFacade`.`WORKFLOW_START_SEND_CONFIG` (
  `VARIABLE_ID` INT NOT NULL COMMENT '',
  `VARIABLE_NAME` VARCHAR(45) NOT NULL COMMENT '',
  `VARIABLE_DATATYPE` VARCHAR(100) NOT NULL COMMENT '',
  `VAR_ADDITONAL_OBJTYPENAME` VARCHAR(100) NULL COMMENT '',
  `VAR_SERIALIZATION_DATAFORMAT` VARCHAR(45) NULL COMMENT '',
  `PARENT_VAR_ID` INT NULL COMMENT '',
  `IS_MANDATORY` TINYINT(1) NOT NULL COMMENT '',
  `WORKFLOW_PROCESS_ID` VARCHAR(100) NULL COMMENT '',
  `IS_START` TINYINT(1) NOT NULL COMMENT '',
  `IS_SENDMESSAGE` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`VARIABLE_ID`)  COMMENT '',
  INDEX `WorkRef_idx` (`WORKFLOW_PROCESS_ID` ASC)  COMMENT '',
  CONSTRAINT `WorkRef`
    FOREIGN KEY (`WORKFLOW_PROCESS_ID`)
    REFERENCES `WorkflowFacade`.`MANAGED_WORKFLOWS` (`WORKFLOW_PROCESS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkflowFacade`.`WORKFLOW_TASK_BUSINESS_FIELD_CONFIG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WorkflowFacade`.`WORKFLOW_TASK_BUSINESS_FIELD_CONFIG` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `WORKFLOW_PROCESS_ID` VARCHAR(100) NULL COMMENT '',
  `TASK_NAME` VARCHAR(45) NULL COMMENT '',
  `FIELD_NAME` VARCHAR(45) NULL COMMENT '',
  `FIELD_DATATYPE` VARCHAR(45) NULL COMMENT 'Complex types are not allowed.',
  `FIELD_DEFAULT_VALUE` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `WORKLOW_REF_1_idx` (`WORKFLOW_PROCESS_ID` ASC)  COMMENT '',
  CONSTRAINT `WORKLOW_REF_1`
    FOREIGN KEY (`WORKFLOW_PROCESS_ID`)
    REFERENCES `WorkflowFacade`.`MANAGED_WORKFLOWS` (`WORKFLOW_PROCESS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
