package com.kanopus.workflow.workflowfacade.entities;


// Generated Aug 13, 2015 10:58:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;


/**
 * ManagedWorkflows generated by hbm2java
 */
public class ManagedWorkflows implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5032760745524786850L;
	private String workflowProcessId;
	private String workflowName;
	private String businesskeyPrefix;
	private String businesskeySuffix;
	private Date createdDate;
	private Date updatedDate;

	public ManagedWorkflows() {
	}

	public ManagedWorkflows(String workflowProcessId) {
		this.workflowProcessId = workflowProcessId;
	}

	public ManagedWorkflows(String workflowProcessId, String workflowName,
			String businesskeyPrefix, String businesskeySuffix,
			Date createdDate, Date updatedDate) {
		this.workflowProcessId = workflowProcessId;
		this.workflowName = workflowName;
		this.businesskeyPrefix = businesskeyPrefix;
		this.businesskeySuffix = businesskeySuffix;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public String getWorkflowProcessId() {
		return this.workflowProcessId;
	}

	public void setWorkflowProcessId(String workflowProcessId) {
		this.workflowProcessId = workflowProcessId;
	}

	public String getWorkflowName() {
		return this.workflowName;
	}

	public void setWorkflowName(String workflowName) {
		this.workflowName = workflowName;
	}

	public String getBusinesskeyPrefix() {
		return this.businesskeyPrefix;
	}

	public void setBusinesskeyPrefix(String businesskeyPrefix) {
		this.businesskeyPrefix = businesskeyPrefix;
	}

	public String getBusinesskeySuffix() {
		return this.businesskeySuffix;
	}

	public void setBusinesskeySuffix(String businesskeySuffix) {
		this.businesskeySuffix = businesskeySuffix;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	

}
