package com.kanopus.workflow.workflowfacade.entities;

//import java.util.HashSet;
//import java.util.Set;

// Generated Aug 13, 2015 10:58:17 AM by Hibernate Tools 3.4.0.CR1


/**
 * RoleMaster generated by hbm2java
 */
public class RoleMaster implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3880514103959015319L;
	private String roleCde;
	private String roleDesc;
//	private RolePrevilige rolePrevilige;
//	private Set<WorkflowRoleConfig> workflowRoleConfigs = new HashSet<WorkflowRoleConfig>(0);
//	private Set<UserRole> userRoles = new HashSet<UserRole>(0);

	public RoleMaster() {
	}

	public RoleMaster(String roleCde) {
		this.roleCde = roleCde;
	}

	public RoleMaster(String roleCde, String roleDesc) {
		this.roleCde = roleCde;
		this.roleDesc = roleDesc;
//		this.rolePrevilige = rolePrevilige;
//		this.workflowRoleConfigs = workflowRoleConfigs;
//		this.userRoles = userRoles;
	}

	public String getRoleCde() {
		return this.roleCde;
	}

	public void setRoleCde(String roleCde) {
		this.roleCde = roleCde;
	}

	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

//	public RolePrevilige getRolePrevilige() {
//		return this.rolePrevilige;
//	}
//
//	public void setRolePrevilige(RolePrevilige rolePrevilige) {
//		this.rolePrevilige = rolePrevilige;
//	}
//
//	public Set<WorkflowRoleConfig> getWorkflowRoleConfigs() {
//		return this.workflowRoleConfigs;
//	}
//
//	public void setWorkflowRoleConfigs(Set<WorkflowRoleConfig> workflowRoleConfigs) {
//		this.workflowRoleConfigs = workflowRoleConfigs;
//	}
//
//	public Set<UserRole> getUserRoles() {
//		return this.userRoles;
//	}
//
//	public void setUserRoles(Set<UserRole> userRoles) {
//		this.userRoles = userRoles;
//	}

}
