package com.kanopus.workflow.workflowfacade.entities;

// default package
// Generated Aug 13, 2015 10:58:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3459636808667375624L;
	private String id;
	private String roleCde;
//	private RoleMaster roleMaster;
//	private UserAuth userAuth;

	public UserRole() {
	}

	public UserRole(String id) {
		this.id = id;
	}

	public UserRole(String id, String roleCde) {
		this.id = id;
		this.roleCde = roleCde;
//		this.roleMaster = roleMaster;
//		this.userAuth = userAuth;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public String getRoleCde() {
		return this.roleCde;
	}
	
	public void setRoleCde(String roleCde) {
		this.roleCde = roleCde;
	}

//	public RoleMaster getRoleMaster() {
//		return this.roleMaster;
//	}
//
//	public void setRoleMaster(RoleMaster roleMaster) {
//		this.roleMaster = roleMaster;
//	}
//
//	public UserAuth getUserAuth() {
//		return this.userAuth;
//	}
//
//	public void setUserAuth(UserAuth userAuth) {
//		this.userAuth = userAuth;
//	}

}
