package com.kanopus.workflow.workflowfacade.entities;

// default package
// Generated Aug 13, 2015 10:58:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * WorkflowRoleConfig generated by hbm2java
 */
public class WorkflowRoleConfig implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4219176679230711379L;
	private WorkflowRoleConfigId id;
	private Boolean canstartinstance;
	private Boolean cansendmessage;

	public WorkflowRoleConfig() {
	}

	public WorkflowRoleConfig(WorkflowRoleConfigId id,
			Boolean canstartinstance, Boolean cansendmessage) {
		this.id = id;
		this.canstartinstance = canstartinstance;
		this.cansendmessage = cansendmessage;
	}

	public WorkflowRoleConfigId getId() {
		return this.id;
	}

	public void setId(WorkflowRoleConfigId id) {
		this.id = id;
	}

	public Boolean getCanstartinstance() {
		return canstartinstance;
	}

	public void setCanstartinstance(Boolean canstartinstance) {
		this.canstartinstance = canstartinstance;
	}

	public Boolean getCansendmessage() {
		return cansendmessage;
	}

	public void setCansendmessage(Boolean cansendmessage) {
		this.cansendmessage = cansendmessage;
	}


	

}
