package com.kanopus.workflow.workflowfacade.entities;

// default package
// Generated Aug 13, 2015 10:58:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * WorkflowStartSendConfig generated by hbm2java
 */
public class WorkflowStartSendConfig implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5022127967243946643L;
	private int variableId;
	private String workflowProcessId;
	private String variableName;
	private String variableDatatype;
	private String varAdditonalObjtypename;
	private String varSerializationDataformat;
	private Integer parentVarId;
	private boolean isMandatory;
	private boolean isStart;
	private boolean isSendmessage;

	public WorkflowStartSendConfig() {
	}

	public WorkflowStartSendConfig(int variableId, String variableName,
			String variableDatatype, boolean isMandatory, boolean isStart,
			boolean isSendmessage) {
		this.variableId = variableId;
		this.variableName = variableName;
		this.variableDatatype = variableDatatype;
		this.isMandatory = isMandatory;
		this.isStart = isStart;
		this.isSendmessage = isSendmessage;
	}

	public WorkflowStartSendConfig(int variableId,
			String workflowProcesssId, String variableName,
			String variableDatatype, String varAdditonalObjtypename,
			String varSerializationDataformat, Integer parentVarId,
			boolean isMandatory, boolean isStart, boolean isSendmessage) {
		this.variableId = variableId;
		this.workflowProcessId = workflowProcesssId;
		this.variableName = variableName;
		this.variableDatatype = variableDatatype;
		this.varAdditonalObjtypename = varAdditonalObjtypename;
		this.varSerializationDataformat = varSerializationDataformat;
		this.parentVarId = parentVarId;
		this.isMandatory = isMandatory;
		this.isStart = isStart;
		this.isSendmessage = isSendmessage;
	}

	public int getVariableId() {
		return this.variableId;
	}

	public void setVariableId(int variableId) {
		this.variableId = variableId;
	}

	public String getWorkflowProcessId() {
		return this.workflowProcessId;
	}

	public void setWorkflowProcessId(String workflowProcessId) {
		this.workflowProcessId = workflowProcessId;
	}

	public String getVariableName() {
		return this.variableName;
	}

	public void setVariableName(String variableName) {
		this.variableName = variableName;
	}

	public String getVariableDatatype() {
		return this.variableDatatype;
	}

	public void setVariableDatatype(String variableDatatype) {
		this.variableDatatype = variableDatatype;
	}

	public String getVarAdditonalObjtypename() {
		return this.varAdditonalObjtypename;
	}

	public void setVarAdditonalObjtypename(String varAdditonalObjtypename) {
		this.varAdditonalObjtypename = varAdditonalObjtypename;
	}

	public String getVarSerializationDataformat() {
		return this.varSerializationDataformat;
	}

	public void setVarSerializationDataformat(String varSerializationDataformat) {
		this.varSerializationDataformat = varSerializationDataformat;
	}

	public Integer getParentVarId() {
		return this.parentVarId;
	}

	public void setParentVarId(Integer parentVarId) {
		this.parentVarId = parentVarId;
	}

	public boolean isIsMandatory() {
		return this.isMandatory;
	}

	public void setIsMandatory(boolean isMandatory) {
		this.isMandatory = isMandatory;
	}

	public boolean isIsStart() {
		return this.isStart;
	}

	public void setIsStart(boolean isStart) {
		this.isStart = isStart;
	}

	public boolean isIsSendmessage() {
		return this.isSendmessage;
	}

	public void setIsSendmessage(boolean isSendmessage) {
		this.isSendmessage = isSendmessage;
	}

}
