package com.kanopus.workflow.workflowfacade.entities;

// default package
// Generated Aug 13, 2015 10:58:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * WorkflowRoleConfigId generated by hbm2java
 */
public class WorkflowRoleConfigId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7479093740969817390L;
	private String roleCde;
	private String workflowProcessId;

	public WorkflowRoleConfigId() {
	}

	public WorkflowRoleConfigId(String roleCde, String workflowProcessId) {
		this.roleCde = roleCde;
		this.workflowProcessId = workflowProcessId;
	}

	public String getRoleCde() {
		return this.roleCde;
	}

	public void setRoleCde(String roleCde) {
		this.roleCde = roleCde;
	}

	public String getWorkflowProcessId() {
		return this.workflowProcessId;
	}

	public void setWorkflowProcessId(String workflowProcessId) {
		this.workflowProcessId = workflowProcessId;
	}

	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorkflowRoleConfigId))
			return false;
		WorkflowRoleConfigId castOther = (WorkflowRoleConfigId) other;

		return ((this.getRoleCde() == castOther.getRoleCde()) || (this
				.getRoleCde() != null && castOther.getRoleCde() != null && this
				.getRoleCde().equals(castOther.getRoleCde())))
				&& ((this.getWorkflowProcessId() == castOther
						.getWorkflowProcessId()) || (this
						.getWorkflowProcessId() != null
						&& castOther.getWorkflowProcessId() != null && this
						.getWorkflowProcessId().equals(
								castOther.getWorkflowProcessId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRoleCde() == null ? 0 : this.getRoleCde().hashCode());
		result = 37
				* result
				+ (getWorkflowProcessId() == null ? 0 : this
						.getWorkflowProcessId().hashCode());
		
		return result;
	}

}
